### ISSUE TITLE
Support for Optional parameters?

### ISSUE THREAD

**Issue by AlpineVibrations** [Maki325/tauri-types#1]
Is there planned support for Option<> parameters?

**Comment by Maki325** [comment]
Hey there @super-fun-surf!
Just did an update for Tauri v2, that allows Option and Result parameters.
It's not backwards compatible with Tauri v1, but if you need that I could probably release a version for it.
If that's all, you can close the issue.

**Comment by AlpineVibrations** [comment]
> Hey there @super-fun-surf!
> Just did an update for Tauri v2, that allows Option and Result parameters.
> It's not backwards compatible with Tauri v1, but if you need that I could probably release a version for it.
> If that's all, you can close the issue.

super rad! excited to check it out! thanks

**Comment by AlpineVibrations** [comment]
and it works. great upgrade. the options are now working
the TS used to error as 
```filename: Option```
and now its working as 
``` filename: string | null;```

thanks much

**Comment by Maki325** [comment]
No problem!
